### ISSUE TITLE
Is this a package only for reaction or can you use to make subscription authorize.net payments?

### ISSUE THREAD

**Issue by sferoze** [taylorsmithgg/reaction-auth-net#2]
Hi,

I am developing cloud subscription software for a customer and they want me to use authorize.net. I found this package forked as a meteor package. Can this be used me to make subscription payment to authorize.net?

**Comment by aaronjudd** [comment]
this is for reaction only, but could pretty easily be used for any meteor application - I just haven't tested it as such so you might need to do some tweaking.
